version: '3'

services:
  frontend:
    container_name: catalog-frontend
    build:
      context: ./catalog-frontend
      dockerfile: Dockerfile
    environment:
      - PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    stdin_open: true
    links:
      - backend
    tty: true
    volumes:
      - ./catalog-frontend:/app
    depends_on:
      - backend
    networks:
      - localhost

  backend:
    build: catalog-backend
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    links:
      - mongodb
    stdin_open: true
    tty: true
    volumes:
      - ./catalog-backend:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - mongodb
    networks:
      - localhost

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    #- "27018:27018"
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '5000:80'

networks:
  localhost:
    driver: bridge
  # environment:
  # NODE_ENV: development
  #depends_on:
  #  - db
  #links:
  #  - db
  #ports:
  #  - '9000:9000'
  #networks:
  #webappnetwork:
  #  driver: bridge
