version: "3"

services:
  mongodb:
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    #depends_on:
    #  - mongodb

  backend:
    build:
      context: ./catalog-backend
    restart: unless-stopped
    #expose:
    #  - ${APP_SERVER_PORT}
    #environment:
    #  API_HOST: ${API_HOST}
    #  APP_SERVER_PORT: ${APP_SERVER_PORT}
    #ports:
    #  - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    stdin_open: true
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./catalog-frontend
      dockerfile: Dockerfile
    stdin_open: true
    #environment:
    #  - PORT=${REACT_APP_PORT}
    #expose:
    #  - ${REACT_APP_PORT}
    #ports:
    #  - ${REACT_APP_PORT}:${REACT_APP_PORT}
    #stdin_open: true

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8000:80"
