version: "3"

services:
  backend:
    build: catalog-backend
    ports:
      - "8000:8000"
    links:
      - mongodb
    stdin_open: true
    tty: true
    volumes:
      - ./catalog-backend:/usr/src/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    #- "27018:27018"
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
  # environment:
  # NODE_ENV: development
  #depends_on:
  #  - db
  #links:
  #  - db
  #ports:
  #  - '9000:9000'
  #networks:
  #webappnetwork:
  #  driver: bridge
