#FROM nginx

#COPY ./default.conf /etc/nginx/conf.d/default.conf


FROM nginx
#COPY nginx.conf /etc/nginx/conf.d/default.conf
# COPY --from=builder /usr/src/app /usr/share/nginx/html
 #COPY /usr/src/app/nginx.conf /etc/nginx/conf.d/default.conf

 COPY ./default.conf /etc/nginx/conf.d/default.conf